
from Activity_Guide_Changes.GaNChangesNorth import import_north_data
from Activity_Guide_Changes.GaNChangesNorth import create_north_paths
from Activity_Guide_Changes.GaNChangesNorth import north_translations
from Activity_Guide_Changes.GaNChangesSouth import create_south_paths
from Activity_Guide_Changes.GaNChangesSouth import import_south_data
from Activity_Guide_Changes.GaNChangesSouth import south_translations
from Activity_Guide_Changes.GaNGetImages import create_image_dir
from Activity_Guide_Changes.GaNGetImages import images_links
from Activity_Guide_Changes.GaNGetImages import images_download
from Activity_Guide_Changes.GaNPrintImages import open_word_doc
from Activity_Guide_Changes.GaNPrintImages import transform_latitude
from Activity_Guide_Changes.GaNPrintImages import open_local_image
from Activity_Guide_Changes.GaNPrintImages import print_local_image
from Activity_Guide_Changes.GaNPrintImages import open_download_image
from Activity_Guide_Changes.GaNPrintImages import print_download_image
from Activity_Guide_Changes.docxToPdf import create_pdf_folder
from Activity_Guide_Changes.docxToPdf import create_pdf_dir
from Activity_Guide_Changes.docxToPdf import create_pdf_paths
from Activity_Guide_Changes.docxToPdf import print_pdf
from Activity_Guide_Changes.docxToPdf import remove_docs



