
from Activity_Guide_Changes.GaN_changes_north import import_north_data
from Activity_Guide_Changes.GaN_changes_north import create_north_paths
from Activity_Guide_Changes.GaN_changes_north import north_translations
from Activity_Guide_Changes.GaN_changes_south import create_south_paths
from Activity_Guide_Changes.GaN_changes_south import import_south_data
from Activity_Guide_Changes.GaN_changes_south import south_translations
from Activity_Guide_Changes.GaN_get_images import create_image_dir
from Activity_Guide_Changes.GaN_get_images import images_links
from Activity_Guide_Changes.GaN_get_images import images_download
from Activity_Guide_Changes.GaN_print_images import open_word_doc
from Activity_Guide_Changes.GaN_print_images import transform_latitude
from Activity_Guide_Changes.GaN_print_images import open_local_image
from Activity_Guide_Changes.GaN_print_images import print_local_image
from Activity_Guide_Changes.GaN_print_images import open_download_image
from Activity_Guide_Changes.GaN_print_images import print_download_image
from Activity_Guide_Changes.docx_to_pdf import create_pdf_folder
from Activity_Guide_Changes.docx_to_pdf import create_pdf_dir
from Activity_Guide_Changes.docx_to_pdf import create_pdf_paths
from Activity_Guide_Changes.docx_to_pdf import print_pdf
from Activity_Guide_Changes.docx_to_pdf import remove_docs




